TaskmasterEndpoint = "tm-service:80"
SamplingStepSize = "1"
MonitoringHost = "http://grafana.monitoring-system.svc:3000"
OSDS_UP_Endpoint = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
x = "/api/datasources/proxy/1/api/v1/query_range?query=ceph_client_io_read_ops"
CEPH_IO_WRITE_OPS = "/api/datasources/proxy/1/api/v1/query_range?query=ceph_client_io_write_ops"
AVG_OSD_APPLY_LATENCY = "/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_perf_apply_latency_seconds)"
BearerToken = "eyJrIjoiNUpKelUyZjRnYUpHUWcxbDB3RUN3ZXhBalFsT1pGWkEiLCJuIjoibW9uaXRvcmluZyIsImlkIjoxfQ=="

AerospikeHost = "ba-aerospike-0.ba-aerospike"
AerospikePort = 3000
AerospikeNamespace = "ba"

WebPort   =            "80"
WebPath  =             "/app/pictures"

Percentiles = [0.01,0.10,0.25,0.50,0.75,0.80,0.90,0.95,0.99]

[Endpoints]
[Endpoints.Endpoint1]
Name="IOPS_write"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_w%5B5m%5D))"
[Endpoints.Endpoint2]
Name="IOPS_read"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_r%5B5m%5D))"
[Endpoints.Endpoint3]
Name="Mon_quorum"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_mon_quorum_count"
[Endpoints.Endpoint4]
Name="Av_capacity"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_cluster_total_used_bytes%2Fceph_cluster_total_bytes"
# [Endpoints.Endpoint5]
# Name="AvMonLat"
# Path="/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_monitor_latency_seconds)"
[Endpoints.Endpoint6]
Name="AvOSDappllat"
Path="/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_apply_latency_ms)"
[Endpoints.Endpoint7]
Name="AvOSDcommlat"
Path="/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_commit_latency_ms)"
[Endpoints.Endpoint8]
Name="TPwrite"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_w%5B5m%5D))"
[Endpoints.Endpoint9]
Name="TPread"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_r%5B5m%5D))"

[Endpoints.Endpoint10]
Name="CEPH_health"
Path="/api/datasources/proxy/1/api/v1/query_range?query=count(ceph_health_status)"
[Endpoints.Endpoint11]
Name="OSDInQuorum"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_in)"
[Endpoints.Endpoint12]
Name="NumCoresTotal"
Path="/api/datasources/proxy/2/api/v1/query_range?query=max(sum(kube_pod_container_resource_requests_cpu_cores)%20by%20(instance))"
[Endpoints.Endpoint13]
Name="UsePercOfMem"
Path="/api/datasources/proxy/2/api/v1/query_range?query=((sum(node_memory_MemTotal)%20-%20sum(node_memory_MemFree)%20-%20sum(node_memory_Buffers)%20-%20sum(node_memory_Cached))%20%2F%20sum(node_memory_MemTotal))%20*%20100"
[Endpoints.Endpoint14]
Name="networkReceive"
Path="/api/datasources/proxy/2/api/v1/query_range?query=sum(rate(node_network_receive_bytes%7Bdevice!~%22lo%22%7D%5B5m%5D))"

[Endpoints.Endpoint15]
Name="networkSend"
Path="/api/datasources/proxy/2/api/v1/query_range?query=sum(rate(node_network_transmit_bytes%7Bdevice!~%22lo%22%7D%5B5m%5D))"
[Endpoints.Endpoint16]
Name="PercUsedCPU"
Path="/api/datasources/proxy/2/api/v1/query_range?query=sum(100%20-%20(avg%20by%20(instance)%20(rate(node_cpu%7Bjob%3D%22node-exporter%22%2Cmode%3D%22idle%22%7D%5B5m%5D))%20*%20100))%20%2F%20count(node_cpu%7Bjob%3D%22node-exporter%22%2Cmode%3D%22idle%22%7D)"
[Endpoints.Endpoint17]
Name="OSD_UP"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoints.Endpoint18]
Name="CPUCoresUsed"
Path="/api/datasources/proxy/2/api/v1/query_range?query=max(sum(kube_pod_container_resource_requests_cpu_cores)%20by%20(instance))"
