TaskmasterEndpoint = "tm-service:80"
SamplingStepSize = "1"
MonitoringHost = "https://monitoring.workshop21.ch"
OSDS_UP_Endpoint = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
AVG_OSD_APPLY_LATENCY = "/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_perf_apply_latency_seconds)"
BearerToken = "eyJrIjoiNUpKelUyZjRnYUpHUWcxbDB3RUN3ZXhBalFsT1pGWkEiLCJuIjoibW9uaXRvcmluZyIsImlkIjoxfQ=="

AerospikeHost = "localhost"
AerospikePort = 3000
AerospikeNamespace = "test"
SampleInterval = 10

RookOSDSelector = "app=rook-ceph-osd"
RookMonSelector = "app=rook-ceph-mon"
RookNamespace = "rook"

Percentiles = [0.01,0.10,0.25,0.50,0.75,0.80,0.90,0.95,0.99]

LenghtRecordsToVerify = 30

WebPort   =            "8080"
WebPath  =             "/tmp"

[Endpoints]
[Endpoints.Endpoint1]
Name="IOPS_write"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_w%5B1m%5D))"
[Endpoints.Endpoint2]
Name="IOPS_read"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_r%5B1m%5D))"
[Endpoints.Endpoint3]
Name="Mon_quorum"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_mon_quorum_count"
[Endpoints.Endpoint4]
Name="Av_capacity"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_cluster_total_used_bytes%2Fceph_cluster_total_bytes*100"
[Endpoints.Endpoint5]
Name="PG_Undersized"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_pg_undersized"
[Endpoints.Endpoint6]
Name="AvOSDappllat"
Path="/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_apply_latency_ms)"
[Endpoints.Endpoint7]
Name="AvOSDcommlat"
Path="/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_commit_latency_ms)"
[Endpoints.Endpoint8]
Name="TPwrite"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_w%5B1m%5D))"
[Endpoints.Endpoint9]
Name="TPread"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(rate(ceph_osd_op_r%5B1m%5D))"

[Endpoints.Endpoint10]
Name="CEPH_health"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_health_status"
[Endpoints.Endpoint11]
Name="OSDInQuorum"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_in)"
[Endpoints.Endpoint12]
Name="NumCoresTotal"
Path="/api/datasources/proxy/2/api/v1/query_range?query=max(sum(kube_pod_container_resource_requests_cpu_cores)%20by%20(instance))"
[Endpoints.Endpoint13]
Name="UsePercOfMem"
Path="/api/datasources/proxy/2/api/v1/query_range?query=max(sum(kube_pod_container_resource_requests_cpu_cores)%20by%20(instance))%20%2F%20min(sum(kube_node_status_allocatable_cpu_cores)%20by%20(instance))%20*%20100"
[Endpoints.Endpoint14]
Name="networkTransmit"
Path="/api/datasources/proxy/2/api/v1/query_range?sum(rate(node_network_transmit_bytes%7Bdevice!~%22lo%22%7D%5B5m%5D))"
[Endpoints.Endpoint15]
Name="PG_Stale"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_pg_stale"
[Endpoints.Endpoint16]
Name="PG_Degraded"
Path="/api/datasources/proxy/1/api/v1/query_range?query=ceph_pg_degraded"
[Endpoints.Endpoint17]
Name="PercUsedCPU"
Path="/api/datasources/proxy/2/api/v1/query_range?query=sum(100%20-%20(avg%20by%20(instance)%20(rate(node_cpu%7Bjob%3D%22node-exporter%22%2Cmode%3D%22idle%22%7D%5B1m%5D))%20*%20100))%20%2F%20count(node_cpu%7Bjob%3D%22node-exporter%22%2Cmode%3D%22idle%22%7D)"
[Endpoints.Endpoint18]
Name="OSD_UP"
Path="/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoints.Endpoint19]
Name="CPUCoresUsed"
Path="/api/datasources/proxy/2/api/v1/query_range?query=max(sum(kube_pod_container_resource_requests_cpu_cores)%20by%20(instance))"
