TaskmasterEndpoint = "tm-service:80"
SamplingStepSize = "10"
MonitoringHost = "https://monitoring.workshop21.ch"
OSDS_UP_Endpoint = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
AVG_OSD_APPLY_LATENCY = "/api/datasources/proxy/1/api/v1/query_range?query=avg(ceph_osd_perf_apply_latency_seconds)"
BearerToken = "eyJrIjoiU1VBeFpZNzBYUGg4Wm83UjBUZjUxOHI4NFlaWUhYc1ciLCJuIjoidmlld2VyIiwiaWQiOjF9"

WebPort   =            "8080"
WebPath  =             "/tmp"

[Endpoints]
    [Endpoint1]
        Name = "IOPS_write"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
    [Endpoint2]
        Name = "IOPS_read"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
    [Endpoint3]
        Name = "Monitors_quorum"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
    [Endpoint4]
        Name = "Available_capacity"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
    [Endpoint5]
        Name = "AverageMonitorLatency"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoint6]
        Name = "Average_OSD_apply_latency"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoint7]
        Name = "Average_OSD_commit_latency"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoint8]
        Name = "Throughput_write"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"
[Endpoint9]
        Name = "Throughput_read"
        Path = "/api/datasources/proxy/1/api/v1/query_range?query=sum(ceph_osd_up)"


[ServiceConfig]
ServiceName = "IKS-V1"
ServicePW = "test1234"
TokenEndpoint = "tkn-service.production.svc.cluster.local:80" 
Scopes = ["IKS-V1"]
Port = ":80"

AerospikeHost = "localhost"
[AerospikeConfig]
AerospikeHosts = ["localhost"]
AerospikePort = 3000